### PR TITLE
added example for vertical navbar branch

### PR DESCRIPTION
**Pull request by kevinpapst**
@cavasinf branch with your changes

### CODE REVIEW

**Comment by kevinpapst** [comment]
@cavasinf upgraded to latest main branch

**Comment by tacman** [comment]
I added a vertical page to my branch, though layout should probably be like light/dark theme, where it sticks if you change it.

image

**Comment by cavasinf** [comment]
I've just checked and nothing wrong for me.

Is something not normal for you @kevinpapst?

Capture d’écran 2022-03-26 à 15 13 52

**Comment by kevinpapst** [comment]
Besides that the badges look really wrong in the menu: did you check the normal pages? The problems were there.

**Comment by cavasinf** [comment]
> Besides that the badges look really wrong

I've tried in the Tabler.io demo. They don't allow us to put badge in first level menu item.
image

Test from here : https://preview.tabler.io/layout-combo.html

**Pull request merged**
